name: Trigger auto deployment for asdfasdfasdfasdf

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/asdfasdfasdfasdf-AutoDeployTrigger-a18f297a-26ed-41df-af92-7285b418a141.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ASDFASDFASDFASDF_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ASDFASDFASDFASDF_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ASDFASDFASDFASDF_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: tmregtest.azurecr.io
          registryUsername: ${{ secrets.ASDFASDFASDFASDF_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ASDFASDFASDFASDF_REGISTRY_PASSWORD }}
          containerAppName: asdfasdfasdfasdf
          resourceGroup: tmauldin-test
          imageToBuild: tmregtest.azurecr.io/asdfasdfasdfasdf:${{ github.sha }}
          dockerfilePath: Dockerfile


