name: Trigger auto deployment for test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/test-AutoDeployTrigger-5ad39bb4-16b2-43fc-b58e-630ce0e9f6d5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: tmregtest.azurecr.io
          registryUsername: ${{ secrets.TEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TEST_REGISTRY_PASSWORD }}
          containerAppName: test
          resourceGroup: tmauldin-test
          imageToBuild: tmregtest.azurecr.io/test:${{ github.sha }}
          dockerfilePath: Dockerfile


