name: Trigger auto deployment for tmtestcontainerapp2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/tmtestcontainerapp2-AutoDeployTrigger-45d431ed-2cbf-40ab-9439-2f464c76fd01.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TMTESTCONTAINERAPP2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TMTESTCONTAINERAPP2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TMTESTCONTAINERAPP2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: tmregtest.azurecr.io
          registryUsername: ${{ secrets.TMTESTCONTAINERAPP2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TMTESTCONTAINERAPP2_REGISTRY_PASSWORD }}
          containerAppName: tmtestcontainerapp2
          resourceGroup: tmauldin-test
          imageToBuild: tmregtest.azurecr.io/tmtestcontainerapp2:${{ github.sha }}
          dockerfilePath: Dockerfile


